/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CustomerWalletRouteImport } from './routes/customer.wallet'
import { Route as CustomerHistoryRouteImport } from './routes/customer.history'
import { Route as CustomerAchievementsRouteImport } from './routes/customer.achievements'
import { Route as AdminIntakeRouteImport } from './routes/admin.intake'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerWalletRoute = CustomerWalletRouteImport.update({
  id: '/customer/wallet',
  path: '/customer/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/customer/history',
  path: '/customer/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAchievementsRoute = CustomerAchievementsRouteImport.update({
  id: '/customer/achievements',
  path: '/customer/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntakeRoute = AdminIntakeRouteImport.update({
  id: '/admin/intake',
  path: '/admin/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/customer/achievements': typeof CustomerAchievementsRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/customer/achievements': typeof CustomerAchievementsRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/customer/achievements': typeof CustomerAchievementsRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/customers'
    | '/admin/intake'
    | '/customer/achievements'
    | '/customer/history'
    | '/customer/wallet'
    | '/admin/'
    | '/customer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/customers'
    | '/admin/intake'
    | '/customer/achievements'
    | '/customer/history'
    | '/customer/wallet'
    | '/admin'
    | '/customer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/customers'
    | '/admin/intake'
    | '/customer/achievements'
    | '/customer/history'
    | '/customer/wallet'
    | '/admin/'
    | '/customer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminIntakeRoute: typeof AdminIntakeRoute
  CustomerAchievementsRoute: typeof CustomerAchievementsRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerWalletRoute: typeof CustomerWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/wallet': {
      id: '/customer/wallet'
      path: '/customer/wallet'
      fullPath: '/customer/wallet'
      preLoaderRoute: typeof CustomerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/history': {
      id: '/customer/history'
      path: '/customer/history'
      fullPath: '/customer/history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/achievements': {
      id: '/customer/achievements'
      path: '/customer/achievements'
      fullPath: '/customer/achievements'
      preLoaderRoute: typeof CustomerAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/intake': {
      id: '/admin/intake'
      path: '/admin/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AdminIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminIntakeRoute: AdminIntakeRoute,
  CustomerAchievementsRoute: CustomerAchievementsRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerWalletRoute: CustomerWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
